#! /bin/sh

export MINC_TOOLKIT=${CONDA_PREFIX}
export MINC_TOOLKIT_VERSION="1.9.17-20180803"

export PATH_MINC_TOOLKIT_SAVE=${PATH}
export ANTSPATH_SAVE=${ANTSPATH}
export PATH=${MINC_TOOLKIT}/pipeline:${PATH}
export PERL5LIB_MINC_TOOLKIT_SAVE=${PERL5LIB}
export PERL5LIB=${MINC_TOOLKIT}/perl:${MINC_TOOLKIT}/pipeline:${PERL5LIB}
export ANTSPATH=${MINC_TOOLKIT}/bin

export MNI_DATAPATH=${MINC_TOOLKIT}/share
export MINC_FORCE_V2=1
export MINC_COMPRESS=4
export VOLUME_CACHE_THRESHOLD=-1
