package:
  name: falcon
  version: "0.9.16.13"

source:
  #git_url: https://github.com/NIST-MNI/falcon.git
  #git_rev: develop-0.9.16
  path: /home/vfonov/src/falcon-gh

requirements:
  build:
    - minc-toolkit-v2 {{ minc_toolkit_v2_ver }} {{ minc_toolkit_v2_var }}
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux and falcon_visual != 'novisual']
    - {{ cdt('libx11') }}     # [linux and falcon_visual != 'novisual']
    - xorg-libx11            # [linux and falcon_visual != 'novisual']
    - xorg-libxrandr         # [linux and falcon_visual != 'novisual']
    - xorg-libxinerama       # [linux and falcon_visual != 'novisual']
    - xorg-libxcursor        # [linux and falcon_visual != 'novisual']
    - xorg-libxi             # [linux and falcon_visual != 'novisual']
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxdamage-devel') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxxf86vm') }}  # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxxf86vm-devel') }}  # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxext') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxext-devel') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxcursor') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxcursor-devel') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxrandr') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxrandr-devel') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxi') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxi-devel') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxinerama') }}     # [linux and falcon_visual != 'novisual']
    - {{ cdt('libxinerama-devel') }}     # [linux and falcon_visual != 'novisual']
  run:
    - minc-toolkit-v2 {{ minc_toolkit_v2_ver }} {{ minc_toolkit_v2_var }}
  host:
    - xorg-libxfixes  # [linux and falcon_visual != 'novisual']
test:
  commands:
    - falcon_cortex_initocs --version
    - falcon_cortex_initics --version
    - falcon_cortex_refine -help

build:
  number: 2
  string: {{ minc_toolkit_v2_var }}_{{ PKG_BUILDNUM }}_{{falcon_visual}}

about:
  home: https://github.com/vfonov/falcon
  license: GPL3
  summary: 'Falcon cortical thickness measurement'
  description: |
    Falcon is a set of tools for cortical thickness measurements
