minctoolkit_variant:
  - noblas
#  - legacy
minctoolkit_visual:
  - novisual
#  - full
hdf5: 1.12.2=nompi_h4df4325_101
libnetcdf: 4.9.0=nompi_h20fbbf5_102
pin_run_as_build:
    libnetcdf:
      max_pin: x.x.x
    hdf5:
      max_pin: x.x.x
c_compiler_version: # [unix]
  - 12.2.0 # [linux]
cxx_compiler_version: 
  - 12.2.0 # [linux]
