minc_toolkit_v2:
   - 1.9.18.9 # =noblas_novisual_h1234567_2
python:
    - 3.10
    - 3.11
    - 3.12
    - 3.13
numpy:
    - 2.2
    - 2.4
    - 2.4
    - 2.4
zip_keys:
  - python
  - numpy
#c_compiler_version: # [unix]
#  - 12.2.0 # [linux]
#cxx_compiler_version: 
#  - 12.2.0 # [linux]
