minc_toolkit_v2:
   - 1.9.18.5 # =noblas_novisual_h1234567_2
#   - 1.9.18.6=noblas_full_h1234567_3
#    - 1.9.19.2
python:
#    - 3.8
    - 3.9
    - 3.10
    - 3.11
    - 3.12
#    - 3.13
numpy:
    - 2.0
    - 2.2
    - 2.3
    - 2.3
zip_keys:
  - python
  - numpy
#c_compiler_version: # [unix]
#  - 12.2.0 # [linux]
#cxx_compiler_version: 
#  - 12.2.0 # [linux]
