{% set name = "minc2-simple" %}
{% set version = "0.2.30.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #url: https://github.com/vfonov/minc2-simple/archive/v2.2.30.tar.gz
  #sha256: 241bf68379f79139d7e07500d49f3f666878ccb86cb7f9c89cdb3e69fc63668b
  path: /home/vfonov/src/minc2-simple

build:
  number: 0
  script: "{{ PYTHON }} python/setup.py install "
#  script: "{{ PYTHON }} -m build python  "
#  script: python -m pip install --no-deps --ignore-installed python

requirements:
  host:
    - numpy
    - pip
    - python
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}
    - cffi
    - six
  build:
    - {{ compiler('c') }}        
    - {{ compiler('cxx') }}      
    - setuptools
    - python
    - pip
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}
    - six
    - cffi
  run:
    - minc-toolkit-v2 {{ minc_toolkit_v2 }}
    - python
    - numpy
    - six
    - cffi

about:
  home: https://github.com/BIC-MNI/pyezminc
  license: GPL2
  summary: 'Python library for MINC IO, using minc2 API and CFFI'
  description: |
    Python library for MINC IO, using minc2 API and CFFI
  dev_url: https://github.com/BIC-MNI/pyezminc

extra:
  recipe-maintainers:
    - vfonov
